---
- name: Update web servers
  hosts: localhost
  remote_user: root
  vars:
   tomcat_version: 9.0.50
   tomcat_download_url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.zip
   tomcat_install_dir: /opt
   tomcat_zipfile: “{{tomcat_install_dir}}/tomcat.zip"
  collections:
   - middleware_automation.jws

  pre_tasks:

- name: "Download latest Jboss"
  
